### ISSUE TITLE
GSM Error kal -s GSM900

### ISSUE THREAD

**Issue by JamesSmi-ux** [steve-m/kalibrate-rtl#32]
Hello guys ! 
Can anyone help me with my problem with kal ? 

root@kali:~# kal -s GSM900
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'GSM900'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.run (/usr/local/lib/node_modules/kal/compiled/command.js:1:2367)
    at Object.<anonymous> (/usr/local/lib/node_modules/kal/scripts/kal:7:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

Thank you !

**Comment by ValZapod** [comment]
apt-get install kalibrate-rtl

And not what you installed.

**Comment by Sharibaloch** [comment]
sudo kal  - s GSM90

**Comment by Sharibaloch** [comment]
sudo kal - s GSM900
